In [10]:
import pandas as pd
import statsmodels.api as sm
df = pd.read_csv("datasets/indian_houseprice_dataset.csv")
df.head()

   Living Area  Bathrooms  Bedrooms  Lot Size  Age  Fireplace    Price
0        1.982        1.0         3      2.00  133          0  14.2212
1        1.676        1.5         3      0.38   14          1  13.4865
2        1.694        2.0         3      0.96   15          1  11.8007
3        1.800        1.0         2      0.48   49          1  13.8297
4        2.088        1.0         3      1.84   29          1  12.9470

In [11]:
df.shape

(1047, 7)

In [12]:
df.isnull().sum()

Living Area    0
Bathrooms      0
Bedrooms       0
Lot Size       0
Age            0
Fireplace      0
Price          0
dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
X = df.drop(columns = ['Price'])   #  Observe , Why the price column is removed here?
# Explain your answer
y = df['Price']

X = sm.add_constant(X)

# Fit the OLS model
model = sm.OLS(y, X).fit()

# Print out the results
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.647
Model:                            OLS   Adj. R-squared:                  0.645
Method:                 Least Squares   F-statistic:                     317.4
Date:                Wed, 06 Aug 2025   Prob (F-statistic):          5.39e-231
Time:                        19:58:46   Log-Likelihood:                -2942.0
No. Observations:                1047   AIC:                             5898.
Df Residuals:                    1040   BIC:                             5933.
Df Model:                           6
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           2.7304      0.609      4.485      0.000       1.536       3.925
Living Area     6.6672      0.342     19.487      0.000       5.996       7.339
Bathrooms       1.6512      0.307      5.371      0.000       1.048       2.255
Bedrooms       -0.5172      0.226     -2.287      0.022      -0.961      -0.073
Lot Size        0.1633      0.164      0.994      0.320      -0.159       0.486
Age            -0.0219      0.004     -5.345      0.000      -0.030      -0.014
Fireplace       1.0207      0.295      3.463      0.001       0.442       1.599
==============================================================================
Omnibus:                      199.393   Durbin-Watson:                   1.636
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              804.303
Skew:                           0.851   Prob(JB):                    2.23e-175
Kurtosis:                       6.942   Cond. No.                         231.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(837, 7)
(210, 7)

In [15]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [16]:
y_pred = lm.predict(X_test)

In [17]:
from sklearn.metrics import r2_score, mean_absolute_error
print(f"r2 score is {r2_score(y_test,y_pred)}")
print(f"mean_absolute_error is {mean_absolute_error(y_test,y_pred)}")

r2 score is 0.6477745304733609
mean_absolute_error is 2.8710764007435836

In [18]:
lm.coef_

array([ 0.        ,  6.49599846,  2.00602321, -0.54424387,  0.26517369,
       -0.01851152,  0.84255832])

In [19]:
lm.intercept_

2.457186320028132

## With own dataset

In [20]:
df = pd.read_csv("datasets/Student_Performance.csv")
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [22]:
x = df.drop(columns=['Extracurricular Activities','Performance Index'])
y = df['Performance Index']

In [23]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(8000, 4)
(2000, 4)

In [24]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [25]:
y_pred = lm.predict(X_test)

In [26]:
from sklearn.metrics import r2_score, mean_absolute_error
print(f"r2 score is {r2_score(y_test,y_pred)}")
print(f"mean_absolute_error is {mean_absolute_error(y_test,y_pred)}")

r2 score is 0.9887144552384186
mean_absolute_error is 1.629672687419702

In [27]:
lm.coef_

array([2.85289351, 1.01703572, 0.47331832, 0.19172629])

In [28]:
lm.intercept_

-33.6020673274929