## With own dataset

In [88]:
import pandas as pd
import numpy as np

In [89]:
df = pd.read_csv("datasets/salary.csv")
df.head()

      City    Education    Industry  YearsExperience        Salary
0    Delhi  High School  Healthcare                6  43493.037602
1    Delhi  High School  Healthcare               19  81589.933296
2  Chennai          PhD     Finance               14  64314.018052
3   Mumbai      Masters          IT               10  54039.967298
4   Mumbai      Masters     Finance                7  46976.401973

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             300 non-null    object
 1   Education        300 non-null    object
 2   Industry         300 non-null    object
 3   YearsExperience  300 non-null    int64
 4   Salary           300 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 11.8+ KB

In [91]:
df.shape

(300, 5)

In [92]:
df.isnull().sum()

City               0
Education          0
Industry           0
YearsExperience    0
Salary             0
dtype: int64

In [93]:
x = df.drop(columns=['Salary'],axis=1)
y = df['Salary']

In [94]:
x.columns

Index(['City', 'Education', 'Industry', 'YearsExperience'], dtype='object')

In [95]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

# Label encode each column
for col in x.columns:
    x[col + '_Encoded'] = le.fit_transform(x[col])
x.head()

,City,Education,Industry,YearsExperience,City_Encoded,Education_Encoded,Industry_Encoded,YearsExperience_Encoded
0,Delhi,High School,Healthcare,6,2,1,2,6
1,Delhi,High School,Healthcare,19,2,1,2,19
2,Chennai,PhD,Finance,14,1,3,1,14
3,Mumbai,Masters,IT,10,4,2,3,10
4,Mumbai,Masters,Finance,7,4,2,1,7

In [96]:
x = x.drop(columns=['City', 'Education', 'Industry', 'YearsExperience'])
x.head()

   City_Encoded  Education_Encoded  Industry_Encoded  YearsExperience_Encoded
0             2                  1                 2                        6
1             2                  1                 2                       19
2             1                  3                 1                       14
3             4                  2                 3                       10
4             4                  2                 1                        7

In [99]:
y.head()

0    43493.037602
1    81589.933296
2    64314.018052
3    54039.967298
4    46976.401973
Name: Salary, dtype: float64

In [100]:
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

In [101]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=42)
print(x_train.shape)
print(x_test.shape)

(240, 4)
(60, 4)

In [102]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [104]:
y_prd = model.predict(x_test)

In [106]:
r2 = r2_score(y_test,y_prd)
mae = mean_absolute_error(y_test,y_prd)
print(f"R2 score is {r2}")
print(f"Mean absolute error is {mae}")

R2 score is 0.9943258029482958
Mean absolute error is 1189.9828221675727

In [107]:
model.coef_

array([  95.95118051, -131.04275984,  -46.78589896, 3008.54561934])

In [108]:
model.intercept_

24982.581661201457